name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Set up examples
        shell: bash
        run: |-
          git clone https://github.com/Bash-it/bash-it examples/bash-it -q --single-branch --depth=1
          git clone https://git.savannah.gnu.org/git/bash.git examples/bash -q --single-branch --depth=1
          git clone https://anongit.gentoo.org/git/repo/gentoo.git examples/gentoo -q --single-branch --depth=1
          if [[ $RUNNER_OS != Windows ]]; then
            git clone https://github.com/oilshell/wild-corpus examples/wild-corpus -q --single-branch --depth=1
          fi
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |-
            examples/*.sh
            examples/bash-it/**/*.sh
            examples/bash-it/**/*.bash
            examples/bash/**/*.sh
            examples/bash/**/*.tests
            examples/gentoo/**/*.sh
            examples/gentoo/**/*.eclass
            examples/wild-corpus/**/*.sh
            # examples/gentoo/**/*.ebuild
            !examples/gentoo/app-antivirus/fangfrisch/files/fangfrisch-has-news.sh
            !examples/gentoo/eclass/ruby-fakegem.eclass
          invalid-files-list: script/known-failures.txt
