name: Fuzz Parser

on:
  push:
    paths:
      - src/scanner.c
  pull_request:
    paths:
      - src/scanner.c
  workflow_dispatch:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/fuzz-action@v4
